features/urls.py
#########################################################################################################
# This script contains navigation links on MopSeq-DB website
# Author: Jean-Christophe Mouren, Maude Jacquot
# Creation date: 2022-05-28
# Last modified: 2024-02-22
#########################################################################################################
from django.urls import path, re_path
from . import views

app_name = 'features'

urlpatterns = [
    path('', views.views_main.home, name='home'),

    re_path(r'^table_pat/(?P<type_p>[\w-]+)/(?P<organism>[\w\ -]+)/$', views.views_table_pat.table_pat, name='table_pat'),
    re_path(r'^download_table_pat/(?P<type_p>[\w-]+)/(?P<organism>[\w\ -]+)/(?P<listDl>[\w-]+)/(?P<idList>[0-9&]+)/$', views.views_table_pat.download_table_pat, name='download_table_pat'),
 
    re_path(r'^info_pat/(?P<organism>[\w\ -]+)/(?P<sample>[\w.-]+)/$', views.views_info_pat.info_pat, name='info_pat'),
    re_path(r'^download_info_pat/(?P<organism>[\w\ -]+)/(?P<sample>[\w.-]+)/(?P<listDl>[\w-]+)/$', views.views_info_pat.download_info_pat, name='download_info_pat'),

    path('about', views.views_main.about, name='about'),
    path('update', views.views_main.update, name='update'),
    path('design', views.views_main.design, name='design'),
    path('analysis', views.views_main.analysis, name='analysis'),
    path('visu_index', views.views_main.visu_index, name='visu_index'),
    path('table_pat_index', views.views_main.table_pat_index, name='table_pat_index'),
    
    re_path(r'^phylogeny/(?P<organism>[\w\ -]+)/$', views.views_phylo_visu.phylogeny, name='phylogeny'),
    re_path(r'^download_phylo/(?P<organism>[\w\ -]+)/$', views.views_phylo_visu.download_phylo, name='download_phylo'),

    path('test', views.views_main.test, name='test'),
] 

mopseq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path(f'{settings.SECRET_ADMIN_KEY}/admin/', admin.site.urls),
    path('', include('features.urls', namespace='features')),
]

#Ici on appelle les urls des applications sous jacente 

templates/analysis.html
{% extends 'base.html' %}  
{% block content %}
{% load static %}

{# Page Heading #}
<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h2 class="font-semibold text-2xl text-gray-800 leading-tight">
            Analysis
        </h2>
    </div>
</header>



<div class="mt-40 flex items-center justify-center">
    <img src="{% static 'img/under_construction.png' %}" alt="navbar brand" class="navbar-brand mt-3" style="width: auto;">
</div>



{% endblock %}

templates/home.html
{% extends 'base.html' %}  
{% block content %}
{% load static %}
{% load features_tags %}

<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        <h1 class="text-5xl  font-bold text-gray-800 leading-tight">
            <span class="text-indigo-700">M</span>o<span class="text-indigo-700">PS</span>eq-<span class="text-indigo-700">DB</span>
        </h1>
        <p class="pt-3">
            <span class="font-semibold">MoPSeq-DB</span> is a user-friendly bioinformatics web application designed for the visualisation of mollusc pathogen sequence data,
             with a primary focus on genome structure, variations and <a class="text-blue-800 hover:underline" href="{% url 'features:visu_index' %}">phylogeny</a>.
            You can learn more about the design and usage of the web application in the <a class="text-blue-800 hover:underline" href="{% url 'features:design' %}">Design</a> tab.
            <a href="{% url 'features:table_pat_index' %}#Viruses"><font color=#2563eb></font></a>
        </p>

        <p class="pt-3 font-semibold">
            <br>
            Browse referenced data in MoPSeq-DB :
            <br>
        </p>

        <div class="flex grid grid-cols-3">
            {% pat_index as dic_pat %}
            {% for key, value in dic_pat.items %}
            {% with imgFName=key|lower %}
            <div class="flex">
                <a href="{% url 'features:table_pat_index' %}#{{ key }}"><font color=#2563eb></font><div class="grid grid-cols-2"><img src="{% static "img/"|add:imgFName|add:".png" %}" style="width: auto; height: 96px;"><div id=key|title  class="self-center font-semibold text-indigo-700 text-xl w-fit pl-3">{{ key }}</div></div></a>
            </div>
            {% endwith %}
            {% endfor %}
        </div>

        <p class="pt-3">
            <br>
            The platform is currently under development and primarily focuses on <a class="text-blue-800 hover:underline" href="{% url 'features:table_pat' type_p='Virus' organism='Ostreid herpesvirus-1' %}">Ostreid herpesviruses (OsHV-1)</a>, <a class="text-blue-800 hover:underline" href="{% url 'features:table_pat'  type_p='Bacteria' organism='Vibrio aestuarianus' %}"><i>Vibrio aestuarianus</i></a> and <a class="text-blue-800 hover:underline" href="{% url 'features:table_pat'  type_p='Protozoan' organism='Perkinsus olseni' %}"><i>Perkinsus olseni</i></a>. As we continue to expand our database, more pathogens will be included in the near future, making it a comprehensive resource for a broader range of mollusc pathogen genomics research.
            <br>
            Join us in exploring MoPSeq-DB and leverage its interactive visualisations to enhance your understanding of mollusc pathogen genomics. Our mission is to contribute to the advancement of pathogen surveillance and diagnostics through this innovative web platform.
        </p>
        <p class="pt-3">
            Source code, documentation and docker container are available in the <a class="text-blue-800 hover:underline" href="https://gitlab.ifremer.fr/bioinfo/mopseq-db"> MoPSeq-DB GitLab repository</a>.
        </p>
    </div>
</header>
{% load static %}
<main class="max-w-7xl mx-auto">
    <div class="flex pt-8 items-center">
        <img src="{% static 'img/nav_db.gif' %}" alt="nav bdd" class="navbar-brand" style="width: auto;max-height: 300px;">
        <div class="pt-3 pl-12 font-medium text-xl">  
            The nucleotide sequences of pathogens are meticulously referenced with clean and 
            <br>organized metadata, and they are readily visualised.    
        </div>
    </div>

    <div class="flex pt-8 items-center">
        <div class="pt-3 pl-5 font-medium text-xl">   
             Users have the ability to download sequence data, annotation files,<br>and metadata files.
        </div>
        <img class="pl-12" src="{% static 'img/dl.gif' %}" alt="dl_expl" class="navbar-brand" style="width: auto;max-height: 300px;">
    </div>

    <div class="flex justify-center font-medium text-xl">
        The platform also offers interactive visualisation of structure (GFF), variations (VCF), and pre-built phylogenetic tree files.
    </div>

    <div class="flex pt-8">
        <img src="{% static 'img/graph.gif' %}" alt="navbar brand" class="navbar-brand" style="width: 600px;max-height: auto;">
        <img class="pl-12" src="{% static 'img/tree.gif' %}" alt="navbar brand" class="navbar-brand" style="width: 600px;max-height: auto;">
    </div>


    <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        <p>
            <span class="font-semibold">Going further:</span> 
        </p>
        <p class="pt-3">
            Upcoming features include support for automatic phylogenetic analysis, specifically the phylogenetic placement of user's sequences. Additionally, the platform will feature an automated submissions tool for new sequences, streamlining the process of adding and updating data.
        </p>
        <p class="pt-3">
            Furthermore, users will benefit from visualising phylogeographic analyses through the integration of Nextstrain modules (<a class="text-blue-800 hover:underline" target="_blank" href="https://doi.org/10.1093/bioinformatics/bty407">Hadfield <i>et al. Bioinformatics,</i> 2018.</a>), providing valuable insights into the geographic distribution and evolutionary history of pathogens.
        </p>
        <p class="pt-3">
            These enhancements will further elevate the capabilities of MoPSeq-DB, making it a cutting-edge and comprehensive resource for researchers and practitioners in the field of mollusc pathogen genomics. We look forward to delivering these exciting features to the scientific community and advancing our collective understanding of pathogen surveillance and diagnostics.
        </p>
    </div>
    

</main>
    {% endblock %}

templates/table_pat_fonctions.html
<script>
    $(document).ready(function(){
        var mytable = $('#table_db').DataTable({ //une variable ajax ici peut contenir toutes les données en avance   
            "pagingType": "full_numbers",
            "searching": true,
            "autoWidth": false,
            "ordering": true,
            //"fixedHeader": true,
            "bStateSave": true, //permet de sauvegarder l'état de la table après refresh notamment les sortings sélectionnés ect 

            "columnDefs": [
                {"targets": 0, "checkboxes": {'selectRow': true}}, //Les checkbox se mettent à la dernière colonne du tableau, celle qui contient les id (clé primaire) de chaque sample enregistré.
                {"width": "50px", "targets": 0},
                {"width": "250px", "targets": 1},
            ],
            'select': {'style': 'multi', 'selector': 'td:first-child'}, // nécessaire pour pouvoir sélectionner plusieurs lignes
            "order": [[2, "asc"]], //on indique que le sorting par défaut de la table

            //{orderable: false, targets: -1},  <!----> Exemple qui annule l'ordering sur une colonne spécifique (ici la dernière) dans le script JS de datable -->

            
        "dom": '<"ul"<"li"l><"li"i>>rt<"bottom"p>',  //https://datatables.net/examples/basic_init/dom.html  Pour placer différemment éléments du datatable 

        "language": { //Pour changer le style des élémens du datable, on peut inclure de l'html dedans 
                "info": "Sequences _START_ to _END_ of _TOTAL_",
                "lengthMenu": '<span class="font-medium ">Item per page:</span> _MENU_'
            },

            "drawCallback": function(settings){ //On supprime la classe des boutons de pagination pour construire la notre 
                var api = new $.fn.dataTable.Api( settings );
                $(".paginate_button", api.table().container())
                    .removeClass("paginate_button")
                    .addClass("w-full border text-base font-medium active:bg-gray-300 bg-white hover:bg-gray-100 px-4 py-2");
            },         
        });    

        $('#myInputTextField').keyup(function(){
            mytable.search($(this).val()).draw() ;
        })  //Fonction pour récupérer la demande de recherche sur la table rentrée dans la barre de recherche en dehors du datatable

        //On cache toutes les colonnes sauf celles que l'on souhaite afficher par défaut
        //mytable.columns().visible(false);
        //mytable.columns([0,1,2,6,8,17,24,25]).visible(true); ici on affiche par défaut certaines colonnes, lignes supprimés car mainteant on regarde quels sont les checkbox cochées
        //Les deux lignes au-dessus sont supprimé car nous préférons vérfié à chaque chargement de la page quel sont les cases cochées
        $('.toggle-vis').each(function() { //on iterate sur tout les objets qui ont la classe toggle-vis au chargement
            if ($(this).prop('checked')==false){  //on regarde si l'attribut checked des checkbox est true ou false 
                if ($(this).attr('data-column') == 10){
                    var column = mytable.column(11);
                    column.visible(false);
                    column = mytable.column(10);
                    column.visible(false);
                }
                else{
                    var column = mytable.column($(this).attr('data-column'));
                    column.visible(false); //on affiche pas les colonnes qui ne sont pas tickées 
                }
                
            }
        });

        //Fonction pour afficher dynamiquement les colonnes du tableau
        $('.toggle-vis').on('click', function(e){  //Le .toggle-vis signifie que n'importe quel élément peut prendre la classe toggle-vis. Si cela avait été a.toggle-vi, seules les balises a auraient pu le prendre.
            if ($(this).attr('data-column') == 10){ //On souhaite afficher la colonne nature of coordinates à chaque fois que les latitutes et longitudes sont demandées
                var column = mytable.column(10);
                column.visible(!column.visible());
                column = mytable.column(11);
                column.visible(!column.visible());
            }
            else{
                // Get the column API object
                var column = mytable.column($(this).attr('data-column')); //on récupère l'id de colonne référencé
                // Toggle the visibility
                column.visible(!column.visible()); //on inverse le statut de la colonne
            }
        });

        $("#btn_dl_pat").click(function(e){ 

            // We get current URL
            var urlcourant = document.location.href;

            // We check if we are on page where the download previously failed, if yes we are deleting the last part of the url
            var re = /download/;
            if (re.test(urlcourant)){
                var re = /=/;
                if (re.test(urlcourant)){
                    urlcourant = urlcourant.replace(/\/$/, "");
                    queue_url = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 ); // We delete two times because the download url takes two supplementary arguments compared to table_pat.html
                    urlcourant = urlcourant.replace(queue_url, "")
                }
                urlcourant = urlcourant.replace(/\/$/, "");
                queue_url = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 ); // We delete two times because the download url takes two supplementary arguments compared to table_pat.html
                urlcourant = urlcourant.replace(queue_url, "")
                urlcourant = urlcourant.replace(/\/$/, "");
                queue_url = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 );
                urlcourant = urlcourant.replace(queue_url, "")
            }
            
            var re = /=/;
            if (re.test(urlcourant)){
                urlcourant = urlcourant.replace(/\/$/, "");
                queue_url = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 ); // We delete two times because the download url takes two supplementary arguments compared to table_pat.html
                urlcourant = urlcourant.replace(queue_url, "")
            }

            // We delete the last / of URL if there is one
            urlcourant = urlcourant.replace(/\/$/, "");
            // We keep the word behind the last / of the URL in a variable, which corresponds to the organism
            queue_url = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 );
            // We do the same for the pathogen type
            urlcourant = urlcourant.replace(queue_url, "")
            urlcourant = urlcourant.replace(/\/$/, "");
            queue_url_2 = urlcourant.substring (urlcourant.lastIndexOf( "/" )+1 );

            var listDl = ""; // We create a string
            $('.to_dl').each(function() { // We go through every element which has the to_dl class
                if ($(this).prop('checked')==true){  // We checked if the element has its checkbox checked
                    listDl += $(this).attr('id_dl'); // If yes we get the id and push it into the string
                }
            });

            var rows_selected = mytable.column(0).checkboxes.selected() // On récupère l'id des samples contenu dans les cellules sélectionnées.
            var id_selected = rows_selected.join("&") // On concatène les ID de la liste avec un symbole & 
            e.preventDefault() //Empêche de charger une nouvelle page

            var url = "{% url 'features:download_table_pat' type_p='xxxx' organism='yyyy' listDl='zzzz' idList='0000' %}"
            url = url.replace('xxxx', queue_url_2)
            url = url.replace('yyyy', queue_url)

            if (listDl != '' && id_selected != ''){
                url = url.replace('zzzz', listDl)
                document.location.href = url.replace('0000', id_selected)
            }else{
                document.location.href = url
            }
        });

        //Classe de bouton pour afficher les colonnes à choisir dans le tableau (classe car plusieurs boutons la partage)
        $('button[class^="btnColumns"]').click(function(){
            $("#divColumns").toggle()

        });

        //Classe pour afficher le div portant l'id correspondant
        $("#btnFilter").click(function(){ 
            $("#divFilter").toggle()
        });
    });
</script>

templates/table_pat_index.html
{% extends 'base.html' %}  
{% block content %}
{% load features_tags %}

{# Page Heading #}
<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h2 class="font-semibold text-2xl text-gray-800 leading-tight">
            Sequence database
        </h2>
    </div>
</header>

<main class="max-w-7xl mx-auto">
    <div class="py-5 px-10">
        <p><span class="font-semibold">MoPSeq-DB</span> aims to provide clean and well-organized genomic data (files/metadata) related to mollusc pathogens. 
            <br>You can access the pathogen database through the index below, where you can browse sequences and their metadata and download relevant files. 
            <br>For detailed explanations, please refer to the "Sharing data" section in the <a class="text-blue-800 hover:underline" href="{% url 'features:design' %}">Design</a> tab.
        </p>

        <ul class="mt-3">
            {% get_kingdom_size as kingdom_size %} {# get_kingdom_size is defined in features/templatetags/features_tags.py #}
            {% get_databases_size as db_size %}
            {% if not dic_pat.items %}
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 italic ">Empty database</div>
            {% else %}
                {% for key, value in dic_pat.items %}
                <li class="w-fit"><div id=key|title  class="font-semibold text-indigo-700 text-xl w-fit">{{ key|title }} ({{ kingdom_size|dictitem:key|title }})</div></li>
                    <ul>
                        {% for element in value %}
                        <li  class="w-fit" ><div class="pl-8 text-lg w-fit italic">{{ element }} ({{ db_size|dictitem:element }})</div>
                            <a class="pl-16 text-blue-800 flex items-center hover:underline" href="{% url 'features:table_pat' type_p=key organism=element %}">Sequence database
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-current h-4 w-4 pb-1" viewBox="0 0 448 512">
                                    <path d="M256 64C256 46.33 270.3 32 288 32H415.1C415.1 32 415.1 32 415.1 32C420.3 32 424.5 32.86 428.2 34.43C431.1 35.98 435.5 38.27 438.6 41.3C438.6 41.35 438.6 41.4 438.7 41.44C444.9 47.66 447.1 55.78 448 63.9C448 63.94 448 63.97 448 64V192C448 209.7 433.7 224 416 224C398.3 224 384 209.7 384 192V141.3L214.6 310.6C202.1 323.1 181.9 323.1 169.4 310.6C156.9 298.1 156.9 277.9 169.4 265.4L338.7 96H288C270.3 96 256 81.67 256 64V64zM0 128C0 92.65 28.65 64 64 64H160C177.7 64 192 78.33 192 96C192 113.7 177.7 128 160 128H64V416H352V320C352 302.3 366.3 288 384 288C401.7 288 416 302.3 416 320V416C416 451.3 387.3 480 352 480H64C28.65 480 0 451.3 0 416V128z"/>
                                </svg>
                            </a>
                        </li> 
                        {% endfor %}
                    </ul>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</main>
{% endblock %}

templates/update.html
{% extends 'base.html' %}  
{% block content %}
{% load static %}
{% load features_tags %}

{# Page Heading #}
<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h2 class="font-semibold text-2xl text-gray-800 leading-tight">
            Updates
        </h2>
    </div>
</header>

{# Page Content #}
<main class="max-w-7xl mx-auto">


    {# Dataset version #}
    <div class="mt-16 font-bold text-2xl text-gray-800 leading-tight">MoPSeq-DB data version </div>
    <div class="pt-1 font-light"> 
        MoPSeq-DB dataset release {% if dbVersion %}{{dbVersion}}{% else %}TEST{% endif %} is available at : <a target="_blank_" class="text-blue-800 hover:underline" href="https://doi.org/10.12770/52134702-4bbd-4c63-af34-9a2cde28e0cc">doi.org/10.12770/52134702-4bbd-4c63-af34-9a2cde28e0cc</a>. 
    </div>


    {# Database size #}
    <div class="mt-16 font-bold text-2xl text-gray-800 leading-tight"> 
        Sequence databases size 
    </div>
    <div>
        <ul class="mt-3">
            {% get_databases_size as db_size %} {# get_databases_size is defined in features/templatetags/features_tags.py #}
            {% if not dic_pat.items %}
                 <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 italic">Empty database</div>
            {% else %}
                {% for key, value in dic_pat.items %}
                    <li class="w-fit"><a class="font-normal text-indigo-700 text-xl w-fit">{{ key|title }}</a></li> 
                        <ul class="pl-7 list-disc">
                            {% if not db_size.items %}
                                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 italic">Empty database</div>
                            {% else %}
                            {% for organism, size in db_size.items %}
                                {% if organism in value %}
                                    <li  class="w-fit" ><a class="pt-5 font-light"><i>{{ organism }}</i> : {{ size }} genomes</a> </li> 
                                {% endif %}  
                            {% endfor %}
                            {% endif %}
                        </ul>
                    
                {% endfor %}
            {% endif %}
        </ul>
    </div>

    {# Software version #}
    <div class="mt-16 font-bold text-2xl text-gray-800 leading-tight"> 
        Software version
    </div>
    <div class="pt-1 font-light"> 
        Software version is {% if version %}{{version}}{% else %}TEST{% endif %}. Source code available at <a target="_blank_"  class="text-blue-800 hover:underline" href="https://gitlab.ifremer.fr/bioinfo/mopseq-db">https://gitlab.ifremer.fr/bioinfo/mopseq-db</a>.
    </div>

    {# Request #}
    <div class="mt-16 font-bold text-2xl text-gray-800 leading-tight"> Suggestion for data addition </div> 
    <div class="pt-1 font-light">For suggestions to data addition, please contact: <a class="text-indigo-700" href="mailto:mopseq@ifremer.fr">mopseq@ifremer.fr</a> </div>

</main>
{% endblock %}

templates/visu_index.html
{% extends 'base.html' %}  
{% block content %}

{# Page Heading #}
<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h2 class="font-semibold text-2xl text-gray-800 leading-tight">
            Pathogens visualisation
        </h2>
    </div>
</header>

<main class="max-w-7xl mx-auto">
    <div class="py-5 px-10">
        <p>Through the index down below, you can access an interactive pre-built phylogenetic tree of pathogen sequence data stored in the <a class="text-blue-800 hover:underline" href="{% url 'features:table_pat_index' %}">sequence database</a>.
            <br>For detailed explanations, refer to the visualisation section in the <a class="text-blue-800 hover:underline" href="{% url 'features:design' %}">Design</a> tab.
        </p>

        <ul class="mt-3">
            {% if not dic_pat.items %} {# the function to get this dict is defined in features/templatetags/features_tags.py and called in templates/base.py #}
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 italic">No visualisation available</div>
            {% else %}
                {% for key, value in dic_pat.items %}
                <li  class="w-fit" ><a class="font-semibold text-indigo-700 text-xl w-fit">{{ key|title }}</a></li>
                    <ul>
                        {% for element in value %}
                        <li  class="w-fit" ><a class="pl-8 text-lg w-fit italic">{{ element }}</a>
                            <a class="pl-16 text-blue-800 flex items-center hover:underline" href="{% url 'features:phylogeny' organism=element %}">Phylogenetic tree
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-current h-4 w-4 pb-1" viewBox="0 0 448 512">
                                    <path d="M256 64C256 46.33 270.3 32 288 32H415.1C415.1 32 415.1 32 415.1 32C420.3 32 424.5 32.86 428.2 34.43C431.1 35.98 435.5 38.27 438.6 41.3C438.6 41.35 438.6 41.4 438.7 41.44C444.9 47.66 447.1 55.78 448 63.9C448 63.94 448 63.97 448 64V192C448 209.7 433.7 224 416 224C398.3 224 384 209.7 384 192V141.3L214.6 310.6C202.1 323.1 181.9 323.1 169.4 310.6C156.9 298.1 156.9 277.9 169.4 265.4L338.7 96H288C270.3 96 256 81.67 256 64V64zM0 128C0 92.65 28.65 64 64 64H160C177.7 64 192 78.33 192 96C192 113.7 177.7 128 160 128H64V416H352V320C352 302.3 366.3 288 384 288C401.7 288 416 302.3 416 320V416C416 451.3 387.3 480 352 480H64C28.65 480 0 451.3 0 416V128z"/>
                                </svg>
                            </a>
                        </li> 
                        {% endfor %}
                    </ul>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</main>
{% endblock %}